name: SampleWorkflow Shell Commands

on: [push]

jobs: 
  run-hello-world:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello World Workflow"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-dependent-job:
    runs-on: windows-latest
    needs: ["run-hello-world"]
    steps:
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python 

      
